INSERT INTO PRODUCT(name, description, price) VALUES('Gato branco','Um gatinho branco','20.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato laranja','Um gatinho laranja','30.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato preto','Um gatinho preto','40.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato branco','Um gatinho branco','200.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato laranja','Um gatinho laranja','450.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato preto','Um gatinho preto','720.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato branco','Um gatinho branco','15.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato laranja','Um gatinho laranja','100.00');
INSERT INTO PRODUCT(name, description, price) VALUES('Gato preto','Um gatinho preto','1200.00');